"""empty message

Revision ID: d1400d6f16a1
Revises: 9069fc31c269
Create Date: 2017-04-10 14:59:31.889544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1400d6f16a1'
down_revision = '9069fc31c269'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=250), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'month', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'month', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'month', type_='foreignkey')
    op.drop_column(u'month', 'user_id')
    op.drop_table('user')
    # ### end Alembic commands ###
